services:
  - name: spiderforce4ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004
    start_command: pm2-runtime start ecosystem.config.js --env production
    environment:
      - NODE_ENV=production
      - PORT=3004