# docker-compose.yml
version: '3.8'

services:
  spiderforce4ai:
    build: .
    container_name: spiderforce4ai
    ports:
      - "3004:3004"
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3004
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G