name: spiderforce4ai
region: fra
services:
  - name: web
    github:
      repo: petertamai/SpiderForce4AI
      branch: main
    build_command: npm install
    run_command: npm run start
    instance_count: 1
    instance_size_slug: basic-s
    http_port: 3004
    envs:
      - key: PORT
        value: "3004"
      - key: NODE_ENV
        value: "production"
      - key: MAX_RETRIES
        value: "2"
      - key: PAGE_TIMEOUT
        value: "30000"
      - key: MAX_CONCURRENT_PAGES
        value: "10"
      - key: AGGRESSIVE_CLEANING
        value: "true"
      - key: REMOVE_IMAGES
        value: "false"